### PR TITLE
Fix: Expand/Collapse toggling

### LINKED ISSUE #1572: Getting Started expand/collapse problem
**Describe the bug**
When I collapse the 'Getting started' group, it expands itself whenever I select a sample query from a different group. 

**To Reproduce**
1. Go to [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer)
2. Collapse the **_Getting Started(8)_** group in the **Sample Queries** tab
3. Expand any other Group, e.g _**Applications(8)**_ and select a query
4. See error described above

**Expected behavior**
The 'Getting Started' group should remain collapsed.

**Desktop (please complete the following information):**
 - OS: Windows]
 - Browser Edge

### PR DESCRIPTION
**Pull request by ElinorW**
## Overview

Fixes #1572
Getting started no longer automatically expands

### Testing Instructions
1. Load GE
2. Collapse 'Getting Started' category
3. Expand 'Applications' category
4. Select a sample query
5. Observe fix.

### CODE REVIEW

File: src/app/views/sidebar/sample-queries/SampleQueries.tsx [hunk 1]
```diff
@@ -276,13 +276,10 @@ const unstyledSampleQueries = (sampleProps?: ISampleQueriesProps): JSX.Element =
...
   const renderGroupHeader = (props: any): any => {
-    const onToggleSelectGroup = () => {
-      props.onToggleCollapse(props.group);
-    };
-
     return (
       <GroupHeader
-        compact={true}
+        {...props}
+        //compact={true}
```
Comment (thewahome) [inline src/app/views/sidebar/sample-queries/SampleQueries.tsx:282]: This comment slipped through

File: src/app/views/sidebar/sample-queries/SampleQueries.tsx [hunk 2]
```diff
@@ -305,8 +300,9 @@ const unstyledSampleQueries = (sampleProps?: ISampleQueriesProps): JSX.Element =
 
   if (selectedQuery) {
     const index = groups.findIndex(k => k.key === selectedQuery.category);
-    if (index !== -1) {
+    if (index !== -1 && index !== 0 ) {
```
Comment (Onokaev) [inline src/app/views/sidebar/sample-queries/SampleQueries.tsx:303]: we can simplify this line to:
if (index > 0)

**Review by Onokaev — APPROVED** [review]
Looks good!

**Review by millicentachieng — APPROVED** [review]
