### PR TITLE
Fix: breaking change with the adaptive cards templating library

### LINKED ISSUE #730: Update to Latest Adaptive cards Library
There's a new release Adaptive Card Templating: https://www.npmjs.com/package/adaptivecards-templating

Here is a blog post that covered the release: https://adaptivecards.io/blog/2020/Templating-RC/. There was a breaking change in the template syntax 

Breaking change in May 2020
Note: If you’ve been using the templating preview, we made a breaking change in the binding syntax. It went from {...} to ${...}.

image

This will solve the unusual rendering happening now in Graph Explorer
 
[AB#6317](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6317)

### PR DESCRIPTION
**Pull request by ElinorW**
## Overview
Updates adaptive card templating library to the latest.
Removes the dollar sign that appears in the new Adaptive Cards templating library.

Fixes #730 

### Demo
Previously...
image

Updated...
image

### CODE REVIEW

File: src/app/services/actions/adaptive-cards-action-creator.ts [hunk 1]
```diff
@@ -50,21 +54,25 @@ export function getAdaptiveCard(payload: string, sampleQuery: IQuery): Function
 
     dispatch(getAdaptiveCardPending());
 
-    return fetch(`https://templates.adaptivecards.io/graph.microsoft.com/${templateFileName}`)
-      .then(resp => resp.json())
+    return fetch(
+      `https://templates.adaptivecards.io/graph.microsoft.com/${templateFileName}`
```
Comment (thewahome) [inline src/app/services/actions/adaptive-cards-action-creator.ts:58]: [Nit] the indenting is off here

Comment (ElinorW) [reply src/app/services/actions/adaptive-cards-action-creator.ts:56]: Which formatting tool is recommended for use?

**Review by thewahome — APPROVED** [review]

File: src/app/services/actions/adaptive-cards-action-creator.ts (hunk 1 above)
Comment (jobala) [reply src/app/services/actions/adaptive-cards-action-creator.ts:56]: @ElinorW #741 adds some vscode settings that will help with the formatting.
