### PR TITLE
Task: use redux toolkit

### LINKED ISSUE #3007: Update to Redux 5.x.x
**Describe the bug**
This [PR]( https://github.com/microsoftgraph/microsoft-graph-explorer-v4/pull/2975) requires the Redux package to be update to v5.

This is a major update with breaking changes 

** Associated changes **
- [x] #3190
- [x] #3191
- [x] #3192
- [x] #3193
- [x] #3194
- [x] #3195
- [x] #3196
- [x] #3197
- [x] #3198
- [x] #3199
- [x] #3200
- [x] #3201
- [x] #3202
- [x] #3203
- [x] #3204
- [x] #3205
- [x] #3206
- [x] #3207
- [x] #3208
- [x] #3209
- [x] #3210
- [x] #3211
- [x] #3256
- [x] #3259
- [x] #3260
- [x] #3265

### LINKED ISSUE #3208: Replace samples actions, action creators and reducers with RTK slices

### LINKED ISSUE #3211: Replace theme actions, action creators and reducers with RTK slices

### PR DESCRIPTION
**Pull request by thewahome**
## Overview
It's increasingly going to get harder to keep redux upto date without breaking changes. Redux Toolkit (RTK) is recommended by the Redux team as it simplifies Redux development. It provides utilities for creating and managing Redux stores, actions, and reducers. 

Using this package will lead to uninstalling `redux`, and `redux-thunk` as RTK simplifies the import process by providing these functionalities under one package. Uninstalling means a few dependencies we do not need to manage

Fixes #3007
Closes #3211 
Closes #3208 

## Testing Instructions

* Load the app
* Perform any and all operations and confirm their success

### CODE REVIEW

File: src/app/middleware/localStorageMiddleware.ts [hunk 1]
```diff
@@ -1,3 +1,4 @@
+import { Middleware } from 'redux';
```
Comment (musale) [inline src/app/middleware/localStorageMiddleware.ts:1]: Question, since in the description you say we're removing this package too, what happens to it's usage in such instances? We create our own types or does RTK offer these too?

Comment (thewahome) [reply src/app/middleware/localStorageMiddleware.ts:1]: RTK packs redux inside it. So we import from the toolkit instead of core  redux

Comment (musale) [reply src/app/middleware/localStorageMiddleware.ts:1]: Oh, noice!

File: src/store/index.ts [hunk 2]
```diff
@@ -40,15 +42,46 @@ const initialState: any = {
...
-export const store = createStore(
-  reducers,
-  initialState,
-  applyMiddleware(...middlewares)
-);
+export type ApplicationState = ReturnType<typeof store.getState>;
+
+export type AppDispatch = ThunkDispatch<ApplicationState, any, AnyAction>;
+
+export type AppStore = Omit<Store<ApplicationState, AnyAction>, 'dispatch'> & {
```
Comment (musale) [inline src/store/index.ts:82]:
```suggestion
export type AppStore = Omit<Store<ApplicationState, UnknownAction>, 'dispatch'> & {
```

File: src/store/index.ts [hunk 3]
```diff
@@ -1,32 +1,34 @@
...
-import { ApplicationState } from '../types/root';
+import { reducers } from '../app/services/reducers';
 
 const loggerMiddleware = createLogger({
   level: 'error',
   collapsed: true
-});
-
-const { NODE_ENV } = process.env;
+}) as Middleware<{}, any, Dispatch<UnknownAction>>;
```
Comment (musale) [inline src/store/index.ts:17]:
```suggestion
}) as Middleware<{}, unknown, Dispatch<UnknownAction>>;
```

File: src/store/index.ts [hunk 4]
```diff
@@ -1,32 +1,34 @@
-import { TypedUseSelectorHook, useSelector } from 'react-redux';
-import { ActionCreator, applyMiddleware, createStore } from 'redux';
+import {
+  AnyAction,
```
Comment (musale) [inline src/store/index.ts:2]:
```suggestion
```

**Review by musale — APPROVED** [review]
🚀 good to go!

**Review by musale — APPROVED** [review]
sudo!!
