### PR TITLE
Fix: Default overlay on collections review panel

### LINKED ISSUE #2376: The Preview Collections tab overlays the entire screen with a white background
**Describe the bug**
After adding resources to a collection and clicking on 'Preview Collection', the overlay applied is white by default. It should blend in with the set theme

**To Reproduce**
1. Go to https://developer.microsoft.com/en-us/graph/graph-explorer
2. Click on Resources
3. Click on any kebab menu
4. Click on 'Add to collections'
5. Click on Preview collections
6. Notice that the area outside the panel is completely white

**Expected behavior**
The overlay should be consistent with other panel overlays e.g Permissions panel overlay

**Screenshots**
image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by Onokaev**
## Overview
Closes #2376 

### Demo

Optional. Screenshots, `curl` examples, etc.

### Notes
The update can be seen on the playwright snapshot diff

## Testing Instructions

* How to test this PR
CLick on the Resources tab
Click on any kebab menu then select Add to collections
Click on Preview collections
Notice the fix

### CODE REVIEW

File: src/app/views/sidebar/resource-explorer/panels/PathsReview.tsx [hunk 1]
```diff
@@ -67,6 +67,10 @@ const PathsReview = (props: IPathsReview) => {
     setSelectedItems(content);
   };
 
+  const panelOverlayProps: IOverlayProps = {
+    isDarkThemed: true
```
Comment (thewahome) [inline src/app/views/sidebar/resource-explorer/panels/PathsReview.tsx:71]: Would it make sense to have this take the true/false value from the current theme?

Comment (Onokaev) [reply src/app/views/sidebar/resource-explorer/panels/PathsReview.tsx:71]: Yes, we can do that. Let me make the change

**Review by ElinorW — CHANGES_REQUESTED** [review]

File: src/app/views/sidebar/resource-explorer/panels/PathsReview.tsx [hunk 2]
```diff
@@ -67,6 +68,23 @@ const PathsReview = (props: IPathsReview) => {
     setSelectedItems(content);
   };
 
+  const isCurrentThemeDark = (): boolean => {
+    if (theme === 'dark' || theme === 'high-contrast') {
+      return true;
+    }
+    return false;
+  }
```
Comment (thewahome) [inline src/app/views/sidebar/resource-explorer/panels/PathsReview.tsx:76]:
```suggestion
  const isCurrentThemeDark = (): boolean => {
    return (theme === 'dark' || theme === 'high-contrast');
  }
```

**Review by thewahome — DISMISSED** [review]

**Review by ElinorW — DISMISSED** [review]
