### PR TITLE
Fix: Update CLI tab to use uppercase

### LINKED ISSUE #2826: The 'Cli' tab should be 'CLI' and should be written the same way in the comments

### PR DESCRIPTION
**Pull request by ElinorW**
## Overview

Fixes #2826 

### Demo
image

## Testing Instructions

* Check out branch
* Navigate to Code snippets tab
* Select CLI tab
* Observe changes

### CODE REVIEW

File: src/app/views/query-response/snippets/snippets-helper.tsx [hunk 1]
```diff
@@ -30,10 +31,12 @@ interface ISupportedLanguages {
 
 export function renderSnippets(supportedLanguages: ISupportedLanguages) {
   const sortedSupportedLanguages: ISupportedLanguages = {};
-  Object.keys(supportedLanguages).sort().forEach(key => {
+  sortedSupportedLanguages.CSharp = supportedLanguages.CSharp;
+  Object.keys(supportedLanguages).filter((language) => language !== 'CSharp').sort().forEach(key => {
```
Comment (calebkiage) [inline src/app/views/query-response/snippets/snippets-helper.tsx:35]: It might be easier to use the [`sort(compareFn)`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort) version of the sort which will save having to filter out csharp first.

**Review by calebkiage — CHANGES_REQUESTED** [review]

File: src/app/views/query-response/snippets/snippets-helper.tsx (hunk 1 above)
Comment (ElinorW) [reply src/app/views/query-response/snippets/snippets-helper.tsx:35]: I don't see how the `compareFn` makes it easier.. I see the alternative as just splicing then unshifting...

Comment (calebkiage) [reply src/app/views/query-response/snippets/snippets-helper.tsx]: I was thinking:

```javascript
Object.keys(supportedLanguages).sort((l1, l2) => {
  if (l1 == 'CSharp') {
    return -1;
  }
  if (l2 == 'CSharp') {
    return 1;
  }
  if (l1 < l2) {
    return -1;
  } else if (l1 > l2) {
    return 1;
  }
  return 0;
})
```

**Review by thewahome — APPROVED** [review]
