### PR TITLE
Fix: Consent type flipping

### LINKED ISSUE #2438: Permissions - consenting to a permission on the list would switch the consent button on the previous permission
On the modify permissions tab, sometimes when I consent to a permission , the consent button turns gray to unconsent. 
If I consent to the permission below on the list, the button on the previous permission flips back to blue (consent)

### PR DESCRIPTION
**Pull request by Onokaev**
## Overview
Closes #2438

### Demo

Optional. Screenshots, `curl` examples, etc.

### Notes
Propagation of consented permissions takes time. As a result, subsequent calls to the token endpoint may not immediately return an already consented scope. This issue is however intermittent. 

## Testing Instructions

* How to test this PR
Sign in with the staging link
Consent to permissions
Notice that the consent button no longer flips

### CODE REVIEW

File: src/app/views/query-runner/request/permissions/Permission.tsx [hunk 1]
```diff
@@ -181,29 +185,29 @@ export const Permission = (permissionProps?: IPermissionProps): JSX.Element => {
...
+    return <div />
   }
 
-  const permissionConsentTypeLabel = (permissionInAllPrincipal : boolean) : JSX.Element => {
-    if(permissionInAllPrincipal){
+  const permissionConsentTypeLabel = (permissionInAllPrincipal: boolean): JSX.Element => {
+    if (permissionInAllPrincipal) {
       return (
-        <div style={{textAlign: 'left', paddingLeft: '10px'}}>
+        <div style={{ textAlign: 'left', paddingLeft: '10px' }}>
```
Comment (calebkiage) [inline src/app/views/query-runner/request/permissions/Permission.tsx:203]: Maybe use `textAlign: 'start` in case the user is working with RTL languages like Arabic.

Comment (calebkiage) [reply src/app/views/query-runner/request/permissions/Permission.tsx:203]: It may also be better to have the padding in a style sheet so changing it is easier.

**Review by calebkiage — COMMENTED** [review]
Left some CSS related comments.

File: src/app/services/actions/permissions-action-creator.ts [hunk 2]
```diff
@@ -193,6 +194,7 @@ export function consentToScopes(scopes: string[]) {
           }))
       }
     } catch (error: any) {
+      console.log('Here is the error', error);
```
Comment (thewahome) [inline src/app/services/actions/permissions-action-creator.ts:197]: Nit: This was forgotten

File: src/app/services/actions/permissions-action-creator.ts [hunk 3]
```diff
@@ -207,6 +209,18 @@ export function consentToScopes(scopes: string[]) {
   };
 }
 
+const correctConsentedScopes = (scopeToBeConsented: string[], consentedScopes: string[],
```
Comment (thewahome) [inline src/app/services/actions/permissions-action-creator.ts:212]: Naming: the function name is unclear. Does it correct the consented scopes or return a set of consented scopes?

File: src/app/views/query-runner/request/permissions/PanelList.tsx [hunk 4]
```diff
@@ -49,7 +49,9 @@ const PanelList = ({ messages,
   const { permissionPanelStyles } = profileStyles(theme);
 
   useEffect(() => {
-    setPermissions(sortPermissions(fullPermissions));
+    if(searchValue === '' && groups.length === 0){
```
Comment (thewahome) [inline src/app/views/query-runner/request/permissions/PanelList.tsx:52]: This could also be null checked like so
```suggestion
    if(!searchValue && groups.length === 0){
```

File: src/app/views/query-runner/request/permissions/Permission.tsx [hunk 5]
```diff
@@ -181,29 +185,29 @@ export const Permission = (permissionProps?: IPermissionProps): JSX.Element => {
   }
 
   const consentTypeProperty = (consented: boolean, item: any): JSX.Element => {
```
Comment (thewahome) [inline src/app/views/query-runner/request/permissions/Permission.tsx:187]: We could probably be clearer by saying what the function does. Does it get/create the consent type property?

File: src/app/services/actions/permissions-action-creator.ts (hunk 3 above)
Comment (Onokaev) [reply src/app/services/actions/permissions-action-creator.ts:212]: It validates the consented scopes. How about 
const validatedScopes = validateConsentedScopes()
The function checks whether all previously consented scopes are available.

File: src/app/views/query-runner/request/permissions/Permission.tsx (hunk 5 above)
Comment (Onokaev) [reply src/app/views/query-runner/request/permissions/Permission.tsx:187]: It should be getConsentTypeProperty

File: src/app/views/query-runner/request/permissions/Permission.tsx (hunk 1 above)
Comment (Onokaev) [reply src/app/views/query-runner/request/permissions/Permission.tsx:203]: The styles have been addressed in a separate PR that was addressing styling on the Modify Permissions tab: https://github.com/microsoftgraph/microsoft-graph-explorer-v4/pull/2445

File: src/app/views/query-runner/request/permissions/Permission.tsx (hunk 5 above)
Comment (Onokaev) [reply src/app/views/query-runner/request/permissions/Permission.tsx]: I've also renamed the other column item headers with proper action verbs

**Review by thewahome — APPROVED** [review]
