### PR TITLE
Fix: Failing link display

### LINKED ISSUE #892: When clicking on Applications > retrieve application properties, Graph Explorer disappears
**Describe the bug**
When using the sample queries, clicking on "Applications > retrieve application properties" makes Graph explorer disappear from the screen.

**To Reproduce**
1. Login to Graph Explorer
1. Go to "Sample queries"
2. Expand "Applications"
3. Click on "retrieve application properties"

**Expected behavior**
The Graph Explorer should stay on my page and I should see the result of my query.

**Screenshots**
GraphExplorerAppProperties

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Version: Version 89.0.774.54 (Official build) (64-bit)
 
[AB#8603](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8603)

### LINKED ISSUE #899: Graph Explorer crashes when you run sample query: POST send channel message
Graph Explorer crashes when you run sample query: POST send channel message

**To Reproduce**
1. Go to graph explorer
2. From the sample queries choose Microsoft Teams > POST send channel message
3. Run the query
4. The explorer crashes and shows nothing

**Expected behavior**
The query runs in the graph explorer and user can see the response/status of response

**Screenshots**
send channel message
image

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Microsoft Edge
 - Version: 89.0.774.54 (Official build) (64-bit)

 
[AB#8665](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8665)

### PR DESCRIPTION
**Pull request by thewahome**
## Overview
Queries with urls in the tip message fail when there are numeric values in the message. 

Fixes #899 
Fixes #892 

### Demo

N/A

### Notes

Made sure to only try and replace the links using the dollar sign

## Testing Instructions

* Run Graph Explorer
* Go to "Sample queries"
* Expand "Applications"
* Click on "retrieve application properties"
* See no error

### CODE REVIEW

File: src/app/views/app-sections/StatusMessages.tsx [hunk 1]
```diff
@@ -4,31 +4,32 @@ import { FormattedMessage } from 'react-intl';
...
     }
 
-
     return parts.map((part: string, index: number) => {
+      const includesLink = matchIncludesLink(matches, part);
       const displayLink = (): React.ReactNode => {
         const link = urls[part];
-        if (link.includes(GRAPH_URL)) {
-          return <Link onClick={() => setQuery(link)}>{link}</Link>;
+        if (link) {
```
Comment (jobala) [inline src/app/views/app-sections/StatusMessages.tsx:24]: This will be cleaner if you use `&&`.

```js
if (link && link.includes(GRAPH_URL)) {
...
}
```

**Review by ElinorW — APPROVED** [review]

File: src/app/views/app-sections/StatusMessages.tsx (hunk 1 above)
Comment (thewahome) [reply src/app/views/app-sections/StatusMessages.tsx:24]: @jobala I am not sure how I would handle the nested nature of the if statements?
Since 
- if there is no link, it should not return anything
- if there is a link it checks
-- should return a clickable graph link if the link is related to the graph URL
-- open a new tab if not related to the graph

Comment (jobala) [reply src/app/views/app-sections/StatusMessages.tsx:24]: I see makes sense.

**Review by jobala — APPROVED** [review]

**Comment by ElinorW** [comment]
does this also fix #910 ??

**Comment by thewahome** [comment]
> does this also fix #910 ?

It should
