### PR TITLE
fix: try-it mode GE view

### LINKED ISSUE #3776: try it view should not have sidebars or some tab items
currently (in **test** environment and **not production**)

Image

How it should look 

Image

It shouldn't have 
- a sidebar
- code snippets
- toolkit component
- adaptive cards

It's also missing the notification bar to indicate it's not the full Graph Explorer experience

### PR DESCRIPTION
**Pull request by Mnickii**
## Overview

Brief description of what this PR does, and why it is needed.

Closes #3776

## Demo
image

### CODE REVIEW

**Review by musale — DISMISSED** [review]

**Comment by ElinorW** [comment]
Could you share screenshot for this

File: src/app/views/query-response/pivot-items/pivot-item.tsx [hunk 1]
```diff
@@ -176,19 +178,23 @@ export const GetPivotItems = () => {
...
-        {selectedValue === translateMessage('Adaptive Cards') && (
-          <ThemeContext.Consumer>
-            {(theme) => (
-              <div id={'adaptive-cards-tab'} tabIndex={0}>
-                <AdaptiveCards
-                  body={body as string}
-                  hostConfig={theme === 'light' ? lightThemeHostConfig : darkThemeHostConfig}
-                />
-              </div>
+        {mode === Mode.Complete && (
```
Comment (ElinorW) [inline src/app/views/query-response/pivot-items/pivot-item.tsx:181]: This condition should be in the tabs definition instead

**Review by ElinorW — DISMISSED** [review]

File: src/app/views/layout/LayoutStyles.tsx [hunk 2]
```diff
@@ -67,5 +67,8 @@ export const useLayoutStyles = makeStyles({
     overflow: 'auto',
     borderRadius: tokens.borderRadiusMedium,
     padding: tokens.spacingHorizontalS
+  },
+  headerMessaging: {
+    margin: '0 10px'
```
Comment (ElinorW) [inline src/app/views/layout/LayoutStyles.tsx:72]: `margin: '10px'`

Comment (Mnickii) [inline src/app/views/layout/LayoutStyles.tsx:72]:
```suggestion
    margin: '10px'
```

**Review by ElinorW — APPROVED** [review]
