### PR TITLE
Fix: ctrl-v error in url

### LINKED ISSUE #428: Bug: CTRL-V doesn't work as expected in URL textbox
**Steps to repro:**
Open Graph Explorer preview
Clear the text in the address bar
Press CTRL-V

**Expected**
To see text from clipboard

**Actual**
GE UI disappears and page scrolls down to just the page footer

### PR DESCRIPTION
**Pull request by thewahome**
## Overview
Pasting something on the url was causing the controls to get lost

Fixes #428 

### Demo

Optional. Screenshots, `curl` examples, etc.

### Notes

Changes the share query function to use the standardized 'parseUrl' method

## Testing Instructions

* Copy an invalid item
* Clear query input
* Paste using Ctrl+V and notice that the page does not error out

### CODE REVIEW

File: src/app/utils/sample-url-generation.ts [hunk 1]
```diff
@@ -7,20 +7,34 @@ export function parseSampleUrl(url: string, version?: string) {
...
-      } catch (error) {
-        search = searchParameters;
-      }
+    try {
+      const urlObject: URL = new URL(url);
+      requestUrl = urlObject.pathname.substr(6).replace(/\/$/, '');
+      queryVersion = (version) ? version : urlObject.pathname.substring(1, 5);
+      search = generateSearchParameters(urlObject, search);
+      sampleUrl = `${GRAPH_URL}/${queryVersion}/${requestUrl + search}`;
+    } catch (error) {
```
Comment (jobala) [inline src/app/utils/sample-url-generation.ts]: Why are we not handling the error?

File: src/app/utils/sample-url-generation.ts [hunk 2]
```diff
@@ -7,20 +7,34 @@ export function parseSampleUrl(url: string, version?: string) {
...
+}
 
-    sampleUrl = `${GRAPH_URL}/${queryVersion}/${requestUrl + search}`;
+function generateSearchParameters(urlObject: URL, search: string) {
+  const searchParameters = urlObject.search;
+  if (searchParameters) {
+    try {
+      search = decodeURI(searchParameters);
+    }
+    catch (error) {
```
Comment (jobala) [inline src/app/utils/sample-url-generation.ts]: Why are we not handling the error?

File: src/app/views/common/share.ts [hunk 3]
```diff
@@ -1,13 +1,18 @@
...
 /**
  * Creates a shareable link
  * @param sampleQuery  The query you want to share ´text´.
  * @param authenticated Optional. Informs the browser that someone is logged in.
  */
 export const createShareLink = (sampleQuery: IQuery, authenticated?: boolean): string => {
-  const { sampleUrl, sampleBody, selectedVerb, selectedVersion } = sampleQuery;
+  const { sampleBody, selectedVerb } = sampleQuery;
+  const { queryVersion, requestUrl, sampleUrl, search } = parseSampleUrl(sampleQuery.sampleUrl);
+  if (!sampleUrl) {
```
Comment (jobala) [inline src/app/views/common/share.ts]: Add a newline between variable definition and conditional statement

File: src/tests/utils/sample-url-generation.spec.tsx [hunk 4]
```diff
@@ -0,0 +1,81 @@
...
+      requestUrl: '',
+      queryVersion: '',
+      sampleUrl: '',
+      search: ''
+    };
+
+    const parsedUrl = parseSampleUrl(url);
+    expect(parsedUrl).toEqual(expectedUrl);
+  });
+
```
Comment (jobala) [inline src/tests/utils/sample-url-generation.spec.tsx]: Unnecessary new lines.
