### PR TITLE
Fix: Adaptive cards color on dark mode

### LINKED ISSUE #2018: Adaptive card colors on dark theme are hard to see
Some of the adaptive cards on dark theme are really hard to see or read. 
Example: https://graph.microsoft.com/v1.0/sites/root 
adaptive cards on dark theme

### PR DESCRIPTION
**Pull request by Onokaev**
## Overview
Fixes #2018 

### Demo
image

### Notes
This problem is only on production. We'll have to deploy to the staging environment with the header and footer injected to confirm that the fix works

## Testing Instructions

* How to test this PR
Run the query https://graph.microsoft.com/v1.0/sites/root
Click on `Adaptive Cards` tab
See fix

### CODE REVIEW

File: src/app/views/query-response/adaptive-cards/AdaptiveCard.tsx [hunk 1]
```diff
@@ -91,6 +91,10 @@ const AdaptiveCard = (props: any) => {
     try {
       adaptiveCard.parse(data.card);
       const renderedCard = adaptiveCard.render();
+      if(renderedCard){
+        renderedCard.style.backgroundColor = currentTheme.palette.whiteTranslucent40;
+        renderedCard.style.color = 'black';
```
Comment (thewahome) [inline src/app/views/query-response/adaptive-cards/AdaptiveCard.tsx:96]: Shouldn't this too get it's colour from the currentTheme palette?

Comment (Onokaev) [reply src/app/views/query-response/adaptive-cards/AdaptiveCard.tsx]: Yes. @ElinorW pointed this out and I already have a fix out

**Review by thewahome — APPROVED** [review]
