### PR TITLE
Fix: Percentage error that causes loss of controls

### LINKED ISSUE #284: Entering '%' causes controls to vanish
**Describe the bug**
When entering a url, using a percent symbol (%) causes all the controls to vanish from the page, leaving only the header and footer.

**To Reproduce**
In the URL box, type the following (copy/paste does not reproduce the error):

```
https://graph.microsoft.com/v1.0/users?$select=displayName,mail&$filter=mail eq 'DiegoS%40M365x214355.onmicrosoft.com'
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge 
 - Version: 80.0.323.0 (Official build) canary (64-bit)

### PR DESCRIPTION
**Pull request by thewahome**
## Overview
When typing in a url to send a request to and the url has a % character. The controls get lost. 
This PR sorts this out.
Fixes #284.

### Notes

Optional. Ancillary topics, caveats, alternative strategies that didn't work out, anything else.

## Testing Instructions

* Try adding a request to the url and enter a % sign
* Note that the controls do not get lost

### CODE REVIEW

File: src/app/utils/sample-url-generation.ts [hunk 1]
```diff
@@ -10,10 +10,17 @@ export function parseSampleUrl(url: string, version?: string) {
     const urlObject: URL = new URL(url);
     requestUrl = urlObject.pathname.substr(6).replace(/\/$/, '');
     queryVersion = (version) ? version : urlObject.pathname.substring(1, 5);
-    search = decodeURI(urlObject.search);
+
+    const searchParameters = urlObject.search;
+    if (searchParameters && searchParameters !== '') {
```
Comment (jobala) [inline src/app/utils/sample-url-generation.ts]: The condition will be fine without the second check  `searchParameters !== ''` . An empty string evaluates to a falsey value.
