### PR TITLE
fix: collections action buttons moving up with few items

### LINKED ISSUE #3730: Collection buttons move up when there are few items
Image

### PR DESCRIPTION
**Pull request by Mnickii**
## Overview

Brief description of what this PR does, and why it is needed.
Closes #3730 

### Demo
Screenshot_28-3-2025_142051_localhost

### CODE REVIEW

**Review by ElinorW — APPROVED** [review]

**Review by musale — APPROVED** [review]

File: src/app/views/sidebar/resource-explorer/collection/CommonCollectionsPanel.tsx [hunk 1]
```diff
@@ -4,6 +4,7 @@ import {
   MessageBar,
   MessageBarBody,
   DrawerFooter,
+  DrawerBody,
```
Comment (Mnickii) [inline src/app/views/sidebar/resource-explorer/collection/CommonCollectionsPanel.tsx:7]:
```suggestion
```
