### PR TITLE
Fix: % symbol crash

### LINKED ISSUE #2265: Typing % in the query fields blanks out the screen
**Describe the bug**
If you type % in the query field the screen instantly blanks out. The console shows "Uncaught URIError: URI malformed" errors.

**To Reproduce**
1. Open Graph Explorer
2. Query field is by default set to "https://graph.microsoft.com/v1.0/me"
3. Type % after "me"

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge, Pale Moon
 - Swedish Input keyboard

### PR DESCRIPTION
**Pull request by thewahome**
## Overview

Fixes #2265 

### Notes

Adding a % in a random location fails the decodeUrl function in the abnf validator.

### CODE REVIEW

**Review by Onokaev — APPROVED** [review]

File: src/modules/validation/abnf.ts [hunk 1]
```diff
@@ -38,10 +38,12 @@ export class ValidatedUrl {
   }
 
   public validate(graphUrl: string): ValidationResult {
+    let decodedGraphUrl = graphUrl;
```
Comment (gavinbarron) [inline src/modules/validation/abnf.ts:41]: Can we please have some tests to validate that we're fixing the issues and not introducing new ones? Or at least one that validates that this fixes an issue?

Why is decodeURI being called? are there values in the encoded version of the string which might cause issues when fed into the parser here?

**Review by gavinbarron — CHANGES_REQUESTED** [review]

File: src/modules/validation/abnf.ts (hunk 1 above)
Comment (thewahome) [reply src/modules/validation/abnf.ts:41]: Yes. The parser requires that the URL be passed in without encoding. Passing a lone % to the parser would cause it to fail the decode step. 

Let me add more tests

Comment (thewahome) [reply src/modules/validation/abnf.ts:41]: @gavinbarron take a look

File: src/modules/validation/abnf.spec.ts [hunk 2]
```diff
@@ -20,7 +20,8 @@ const validUrls = [
 
 const invalidUrls = [
   'https://graph.microsoft.com/me+you',
-  'https://graph.microsoft.com/v1.0/me/messages?$$select=id'
+  'https://graph.microsoft.com/v1.0/me/messages?$$select=id',
+  'https://graph.microsoft.com/v1.0/me/drive/root:/Encoded%'
```
Comment (gavinbarron) [inline src/modules/validation/abnf.spec.ts:24]: Encoded characters are a % followed by 2 hex digits
```suggestion
  'https://graph.microsoft.com/v1.0/me/drive/root:/Encoded%',
  'https://graph.microsoft.com/v1.0/me/drive/root:/Encoded%2'
```
