### PR TITLE
Fix: Permissions scrollbar

### LINKED ISSUE #2563: Scrollbar appears at the wrong position on the Modify Permissions tab
**Describe the bug**
The scrollbar appears at the wrong position for cases where the permissions items do not fill the entire tab and a horizontal scrollbar is rendered

**To Reproduce**
1. Go to https://developer.microsoft.com/en-us/graph/graph-explorer
2. Type the query `https://graph.microsoft.com/v1.0/me/photo`
3. Click on the Modify Permissions tab
4. Resize the screen towards the Mobile view until a scrollbar appears on the tab
5. Notice the positioning of the scrollbar

**Expected behavior**
The scrollbar should appear at the bottom of the tab

**Screenshots**
image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by Onokaev**
## Overview
Closes #2563 

### Demo
Screenshot 2023-05-16 at 12 18 54 PM

### Notes
The DetailsList component has a wrapper div that is added at runtime with a classname of ms-ViewPort. So, we have to add css rules to the div dynamically

## Testing Instructions

* How to test this PR
1. Resize the screen so that the app is in mobile view. 
2. Type the query: https://graph.microsoft.com/v1.0/me/photo on the query textbox
3. Click on the Modify Permissions tab
4. Notice that the scrollbar that appears is at the bottom of the tab

### CODE REVIEW

File: src/app/views/query-runner/request/util.ts/CssHelpers.ts [hunk 1]
```diff
@@ -0,0 +1,14 @@
+// DetailsList has a wrapper div that is added at runtime with the classname
```
Comment (ElinorW) [inline src/app/views/query-runner/request/util.ts/CssHelpers.ts:1]: You could try adding the height property on the .scss file to achieve the same without having to add this function

**Review by ElinorW — CHANGES_REQUESTED** [review]

File: src/app/views/query-runner/request/util.ts/CssHelpers.ts (hunk 1 above)
Comment (ElinorW) [reply src/app/views/query-runner/request/util.ts/CssHelpers.ts:1]: Also, I think it's worth investigating the parent heights... There may be some wrong configurations set

**Review by ElinorW — APPROVED** [review]
