### PR TITLE
Fix: create onenote page

### LINKED ISSUE #331: Example query fails with Preview Graph Explorer, succeeds in currently released Graph Explorer
Refer to this Issue reported in GE V3: https://github.com/microsoftgraph/microsoft-graph-explorer/issues/390
[AB#6143](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6143)

### LINKED ISSUE #491: "Parsing Select and Expand failed." error when expanding singleValueExtendedProperties
Describe the bug
Getting singleValueExtendedProperties does not work in graph explorer preview event it works   in  https://developer.microsoft.com/en-us/graph/graph-explorer
To Reproduce

Run following query
https://graph.microsoft.com/v1.0/me/events/{event-id}?$expand=singleValueExtendedProperties($filter=id eq 'String {00020329-0000-0000-c000-000000000046} Name myprop1')

See error

{
    "error": {
        "code": "BadRequest",
        "message": "Parsing Select and Expand failed.",
        "innerError": {
            "request-id": "79e359fc-05da-46fa-858b-fef70a9142c3",
            "date": "2020-04-28T18:14:39"
        }
    }
}

Expected behavior
This query should give proper event response as general   graph-explorer
[AB#6142](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6142)

### LINKED ISSUE #573: Filter on Sharepoint Items not working due to too long Endpoint call.
Describe the bug
When I am trying to target specific Sharepoint Items using the Graph Explorer, is does not work. The same problem happens when you use graphClient, and put everything into the .api()
Whenever I create a very long REST-Api call it gets cut off at (I guess around +-255 characters)
To Reproduce

Go to 'Graph Explorer'
Fill out the following QUery:

https://graph.microsoft.com/v1.0/sites/DevTenantForTesting.sharepoint.com,a8e3e990-da7f-4f09-8aea-85911fd5eb5b,8be9c9ae-d580-459b-a763-e2dfcff52731/lists/97ee04f3-9a1b-401a-804d-386002970233/items?$expand=fields($select=Field1,Field2,Field4)

Open F12, check the Network calls.
See error that is is trying to call the following:

https://graph.microsoft.com/v1.0/sites/DevTenantForTesting.sharepoint.com,a8e3e990-da7f-4f09-8aea-85911fd5eb5b,8be9c9ae-d580-459b-a763-e2dfcff52731/lists/97ee04f3-9a1b-401a-804d-386002970233/items?$expand=fie
Expected behavior
The previous version of MS Graph Explorer did not have this problem. It came up today as I can no longer access the old version  of Graph Explorer...
Screenshots

Desktop (please complete the following information):
Chrome Browser
Additional context
[AB#6141](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6141)

### LINKED ISSUE #589: "Parsing Select and Expand failed" error only on microsoft-graph-explorer
Describe the bug
Expand query is breaking in following query and it is only happening in graph explorer .but same url is working with graph sdk client and postmen
https://graph.microsoft.com/v1.0/users/{user-id}/events?startDateTime=2020-04-10T00:00:00&endDateTime=2021-04-10T00:00:00 	&$expand=singleValueExtendedProperties($filter=id eq 'String {00020329-0000-0000-c000-000000000046} Name BookingId')   
Error response
{
    "error": {
        "code": "BadRequest",
        "message": "Parsing Select and Expand failed.",
        "innerError": {
            "date": "2020-06-24T09:15:02",
            "request-id": "d6856fbe-xxxx-xxxx-xxxx-b8e29c75b448"
        }
    }
}

Fiddler Screenshots of graph explorer query

Expected behavior
Query must work same as graph sdk/postmen
[AB#6140](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6140)

### LINKED ISSUE #598: Under what circumstances would a user not be able to create a OneNote page using Graph Explorer?
Use the issues in this repository to open issues about the Graph Explorer application. Questions about the Microsoft Graph should be directed to StackOverflow. Use the [microsoftgraph] tag on StackOverflow.
Expected behavior
After logging in I am able to use graph explorer to see my notebooks and their sections
When I click on create  a section a template is copied in the query line where the user is supposed to fill in the notebook-id and then press "Run query"
Similar behavior is expected for "Create page" nothing happens. Is that expected?
Actual behavior
When I click on "Create page" nothing happens
Steps to reproduce the behavior
I use  a MS Account, and I login in in MS Graph Explored
Then I try to create a page.
HTTP traffic capture
N/A
[AB#6144](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6144)

### LINKED ISSUE #729: $whatif not working on Graph Explorer
**Describe the bug**
$whatif does not work for Microsoft tenant in Graph Explorer
**To Reproduce**
1. Go to Graph Explorer while not logged in 
2. Paste this: https://graph.microsoft.com/v1.0/me?$whatif
3. This works
4. Try the same query while logged in Microsoft tenant
5. Fails.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by thewahome**
## Overview

- [X] Enables the display of xml content in the request body
- [x] Updates the `microsoft-graph-sdk` to the latest version to support sending of the html content

Fixes #598 

Updating to the latest sdk :
Fixes #573 
Fixes #589
Fixes #491 
Fixes #331
Fixes #729

### CODE REVIEW

File: src/app/services/actions/query-action-creator-util.ts [hunk 1]
```diff
@@ -100,12 +100,16 @@ const makeRequest = (httpVerb: string, scopes: string[]): Function => {
 
     if (query.sampleHeaders && query.sampleHeaders.length > 0) {
       query.sampleHeaders.forEach(header => {
-
-        // We are relying on the graph client to set the content type header.
+        // We are relying on the graph client to set the 'application/json' content type header.
```
Comment (ddyett) [inline src/app/services/actions/query-action-creator-util.ts:103]: might be clearer to say javascript SDK

File: src/app/services/actions/query-action-creator-util.ts [hunk 2]
```diff
@@ -100,12 +100,16 @@ const makeRequest = (httpVerb: string, scopes: string[]): Function => {
...
         if (header.name.toLowerCase() === 'content-type') {
-          return;
+          if (header.value !== 'application/json') {
+            sampleHeaders[header.name] = header.value;
+          } else {
+            return;
```
Comment (ddyett) [inline src/app/services/actions/query-action-creator-util.ts:108]: the comment above should probably just above this return to indicate why you just return.

File: src/app/views/sidebar/sample-queries/SampleQueries.tsx [hunk 3]
```diff
@@ -259,7 +260,13 @@ export class SampleQueries extends Component<ISampleQueriesProps, any> {
         }
         telemetry.trackEvent(RUN_QUERY_EVENT, sampleQuery);
       } else {
-        sampleQuery.sampleBody = (sampleQuery.sampleBody) ? JSON.parse(sampleQuery.sampleBody) : undefined;
+        if (sampleQuery.sampleBody) {
+          if (isJsonString(sampleQuery.sampleBody)) {
+            sampleQuery.sampleBody = JSON.parse(sampleQuery.sampleBody);
+          }
+        } else {
+          sampleQuery.sampleBody = undefined;
```
Comment (ddyett) [inline src/app/views/sidebar/sample-queries/SampleQueries.tsx:268]: why do you need this based on the if above

File: src/app/views/sidebar/sample-queries/SampleQueries.tsx [hunk 4]
```diff
@@ -259,7 +260,13 @@ export class SampleQueries extends Component<ISampleQueriesProps, any> {
         }
         telemetry.trackEvent(RUN_QUERY_EVENT, sampleQuery);
       } else {
-        sampleQuery.sampleBody = (sampleQuery.sampleBody) ? JSON.parse(sampleQuery.sampleBody) : undefined;
+        if (sampleQuery.sampleBody) {
```
Comment (ddyett) [inline src/app/views/sidebar/sample-queries/SampleQueries.tsx:263]: i think these two lines can be combined.

File: src/app/views/sidebar/sample-queries/sample-query-utils.ts [hunk 5]
```diff
@@ -0,0 +1,11 @@
+export function isJsonString(str: string) {
+  try {
+    const parsedString = JSON.parse(str);
+    if (parsedString && typeof parsedString === 'object') {
+      return true;
+    }
+  } catch (e) {
+    return false;
```
Comment (ddyett) [inline src/app/views/sidebar/sample-queries/sample-query-utils.ts:8]: might be good to log out here for debugging purposes.

File: src/app/services/actions/query-action-creator-util.ts (hunk 1 above)
Comment (jobala) [inline src/app/services/actions/query-action-creator-util.ts:103]: Will setting the `application/json` header break the SDK?

File: src/app/views/sidebar/sample-queries/sample-query-utils.ts [hunk 6]
```diff
@@ -0,0 +1,11 @@
+export function isJsonString(str: string) {
```
Comment (jobala) [inline src/app/views/sidebar/sample-queries/sample-query-utils.ts:1]: Since `JSON.parse` throws an error when called with invalid json string, this can be simplified to

```javascript
export function isJsonString(str): boolean {
  try {
    JSON.parse(str)
    return true
  } catch (error) {
    return false
  }
}
```

**Review by jobala — CHANGES_REQUESTED** [review]

File: src/app/services/actions/query-action-creator-util.ts (hunk 1 above)
Comment (thewahome) [reply src/app/services/actions/query-action-creator-util.ts:103]: Just checked this out. 
The SDK was previously sending the request with multiple `Content-type: application/json` headers if we add them here. That's why we removed the header.

I have now tested. It looks like the latest update fixes this for us too

**Review by MIchaelMainer — APPROVED** [review]
