### PR TITLE
Fix: enter key runs previous query

### LINKED ISSUE #2338: ENTER keyboard shortcut to run the current query is broken
**Describe the bug**
Pressing ENTER instead of clicking Run Query will run the previous query instead of the current one.

**To Reproduce**
1. Go to https://aka.ms/ge
2. change `/me` in the url to `/users`
3. remain with the cursor focus on the textbox, and press enter

**Expected behavior**
`/users` response should execute

**Actual behavior**
`/me` response is executed (previous request)

Note: pressing the "Run Query" button will execute the current request.

### PR DESCRIPTION
**Pull request by thewahome**
## Overview

Fixes #2338 

### Notes

It fails for the use case where a user types in something and it is the only thing in the suggestions. Since we didn't assume this becomes the selected suggestion, the query doesn't get changed.

It is fixed by appending the suggestion to the URL

## Testing Instructions

* Run `/me`
* Change `me` to `users`
* Hit enter
* Notice the results for `/users` in the response

### CODE REVIEW

File: src/app/views/query-runner/query-input/auto-complete/AutoComplete.tsx [hunk 1]
```diff
@@ -58,6 +58,7 @@ const AutoComplete = (props: IAutoCompleteProps) => {
     const targetValue = e.target.value;
     setQueryUrl(targetValue);
     props.contentChanged(targetValue);
+    console.log(targetValue)
```
Comment (Onokaev) [inline src/app/views/query-runner/query-input/auto-complete/AutoComplete.tsx:61]: Must have forgotten this :)

Comment (thewahome) [reply src/app/views/query-runner/query-input/auto-complete/AutoComplete.tsx]: Nice catch

**Review by Onokaev — APPROVED** [review]

**Review by ElinorW — APPROVED** [review]
