### PR TITLE
fix: use initials in profile icon when signed in

### LINKED ISSUE #3626: Use initials on profile icon when signed in

### PR DESCRIPTION
**Pull request by Mnickii**
## Overview

Closes #3626 

Brief description of what this PR does, and why it is needed.

### Demo
screenshot-1739804149612

### CODE REVIEW

File: src/app/views/authentication/profile/ProfileV9.tsx [hunk 1]
```diff
@@ -147,18 +147,23 @@ const SignedInButton = forwardRef<
   React.ComponentProps<typeof Button>
 >((props, ref) => {
   const styles = useHeaderStyles();
+  const profile = useAppSelector((state) => state.profile);
+  const user = profile.user;
```
Comment (musale) [inline src/app/views/authentication/profile/ProfileV9.tsx:151]:
```suggestion
  const user = useAppSelector((state) => state.profile.user);
```
Just a nit. This is all good to go.

**Review by musale — APPROVED** [review]

**Review by ElinorW — APPROVED** [review]
