### PR TITLE
Fix: Adaptive cards changes

### LINKED ISSUE #865: Additional changes on the Adaptive cards tab
The following changes were suggested to the Adaptive cards tab:
1. Change the name of the JSON Schema tab to **JSON template** (**small t)
2. Add a link to adaptive cards designer on the banner so the text is "Get started with adaptive cards on [Adaptive cards templating SDK](https://docs.microsoft.com/en-us/adaptive-cards/templating/sdk) and experiment on [Adaptive cards designer](https://www.adaptivecards.io/designer/)"
3. Show the code before the binding happens so developers can just copy and paste in their apps
4. Add a copy button on the code tab 
[AB#8311](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8311)

### PR DESCRIPTION
**Pull request by ElinorW**
## Overview

- [x] Renamed tab from JSON Schema to  JSON template.
- [x] Modified the message that appears to 'Get started with adaptive cards on Adaptive Cards Templating SDK and experiment on Adaptive Cards designer.'
- [x] Displays the template payload, without the actual card values.

Fixes #865 

### Demo

image

### CODE REVIEW

File: src/app/services/actions/adaptive-cards-action-creator.ts [hunk 1]
```diff
@@ -54,38 +54,38 @@ export function getAdaptiveCard(
...
+function createCardFromTemplate(templatePayload: any, payload: string) {
+  const template = new AdaptiveCardsTemplateAPI.Template(templatePayload);
+  const context: AdaptiveCardsTemplateAPI.IEvaluationContext = {
+    $root: payload,
+  };
+  AdaptiveCardsTemplateAPI.GlobalSettings.getUndefinedFieldValueSubstitutionString = (
+    path: string
+  ) => ' ';
+  const card = template.expand(context);
+  return card;
```
Comment (thewahome) [inline src/app/services/actions/adaptive-cards-action-creator.ts:89]: This can be returned immediately without the need to declare it

**Review by thewahome — APPROVED** [review]
