### PR TITLE
Task: Migrate from webpack v4 to webpack v5

### LINKED ISSUE #1365: Update dependencies with security alerts
**Describe the bug**
Update dependencies on our security tab

**Screenshots**
image

### LINKED ISSUE #1393: Migrate from webpack v4 to webpack v5
The new version seeks to:

- Improve build performance 
- Improve Long Term Caching with better algorithms and defaults.
- Improve bundle size 
- Improve compatibility with the web platform.

This upgrade also enables us to update some dependencies with security risks which could only work with the updated webpack v5 package

Related to issue #1365

### PR DESCRIPTION
**Pull request by ElinorW**
## Overview
This PR 
- migrates GE from using webpack v4 to webpack v5.
- migrates GE's webpack dev server from v3 to v4.
- updates related loaders and plugins to more stable versions
- updates multiple config files
- as a result, fixes the dependencies with security risks

Fixes #1365 , fixes #1393

### CODE REVIEW

File: src/modules/authentication/AuthenticationWrapper.ts [hunk 1]
```diff
@@ -44,7 +44,7 @@ export class AuthenticationWrapper implements IAuthenticationWrapper {
     try {
       return await this.getAuthResult([], sessionId);
     } catch (error) {
-      throw error;
+      throw new Error(`${error}`);
```
Comment (millicentachieng) [inline src/modules/authentication/AuthenticationWrapper.ts:47]: Why is this necessary?

File: src/app/utils/graph-toolkit-lookup.ts [hunk 2]
```diff
@@ -8,7 +8,7 @@ export function lookupToolkitUrl(sampleQuery: IQuery) {
     const { requestUrl, search } = parseSampleUrl(sampleQuery.sampleUrl);
     const query = '/' + requestUrl + search;
     for (const templateMapKey in templates) {
-      if (templates.hasOwnProperty(templateMapKey)) {
+      if (Object.prototype.hasOwnProperty.call(templates, templateMapKey)) {
```
Comment (millicentachieng) [inline src/app/utils/graph-toolkit-lookup.ts:11]: Why the change?

Comment (ElinorW) [reply src/app/utils/graph-toolkit-lookup.ts:11]: This is because of the eslint update, leaving it as is presents and error. 
Reference this https://eslint.org/docs/rules/no-prototype-builtins

File: src/modules/authentication/AuthenticationWrapper.ts (hunk 1 above)
Comment (ElinorW) [reply src/modules/authentication/AuthenticationWrapper.ts:47]: So leaving it as is presents an eslint error. This one https://eslint.org/docs/rules/no-useless-catch
I wasn't quite sure what to do because we have quite a number of these try-catch blocks that only throw an error...
Do you have any suggestive fix?

File: src/app/services/actions/profile-action-creators.ts [hunk 3]
```diff
@@ -84,7 +84,7 @@ async function getProfileInformation(): Promise<IUser> {
     profile.emailAddress = userInfo.mail || userInfo.userPrincipalName;
     return profile;
   } catch (error) {
-    throw error;
+    return profile;
```
[the remark this answers is not in the document]
Comment (ElinorW) [reply src/app/services/actions/profile-action-creators.ts:87]: Oh yeah , though I can't just throw the error as this creates an eslint error.. (ref: https://eslint.org/docs/rules/no-useless-catch)
I guess we could disable the eslint rule, or I'm open to a different way of handling the error if you have a suggestion

[the remark this answers is not in the document]
Comment (millicentachieng) [reply src/app/services/actions/profile-action-creators.ts:87]: Since the error is being handled in the calling function, you can remove the try...catch in this function.

File: src/modules/authentication/AuthenticationWrapper.ts (hunk 1 above)
Comment (millicentachieng) [reply src/modules/authentication/AuthenticationWrapper.ts:47]: You can remove the try...catch statements since they are not really useful here.

File: src/app/services/actions/profile-action-creators.ts (hunk 3 above)
[the remark this answers is not in the document]
Comment (thewahome) [reply src/app/services/actions/profile-action-creators.ts:87]: Without the try...catch throwing an error, would the error be caught by the calling function?

File: src/app/services/actions/profile-action-creators.ts [hunk 4]
```diff
@@ -83,8 +83,8 @@ async function getProfileInformation(): Promise<IUser> {
     profile.displayName = userInfo.displayName;
     profile.emailAddress = userInfo.mail || userInfo.userPrincipalName;
     return profile;
-  } catch (error) {
-    return profile;
+  } catch (error: any) {
+    throw new Error('Failed to get profile information - ' + error.toString());
```
Comment (Onokaev) [inline src/app/services/actions/profile-action-creators.ts:87]: you forgot to localize this string

File: src/modules/authentication/AuthenticationWrapper.ts [hunk 5]
```diff
@@ -101,8 +102,8 @@ export class AuthenticationWrapper implements IAuthenticationWrapper {
     try {
       const response: AuthenticationResult = await msalApplication.acquireTokenSilent(silentRequest);
       return response;
-    } catch (error) {
-      throw new Error(`${error}`);
+    } catch (error: any) {
+      throw new Error(translateMessage('Failed to get token - ' + error.toString()));
```
Comment (Onokaev) [inline src/modules/authentication/AuthenticationWrapper.ts:106]: Remember to add the localized string to GE.json file

File: src/app/services/actions/profile-action-creators.ts (hunk 4 above)
Comment (ElinorW) [reply src/app/services/actions/profile-action-creators.ts:87]: Oh yeah! Nice catch!

**Review by thewahome — APPROVED** [review]

**Review by Onokaev — APPROVED** [review]
