### PR TITLE
Fix: Text-alignment on the text in query response tabs

### LINKED ISSUE #2019: Text not centered
Both on the Toolkit Component tab and the Adaptive Cards tab, when a component/card is not available, the text appearing on the screen is not centered forcing the user sometimes to scroll while there's enough space . 
adaptive card text
MGT text

### PR DESCRIPTION
**Pull request by MaryannGitonga**
## Overview

Closes #2019 

### Demo

image

image

## Testing Instructions

* How to test this PR

- Checkout to fix/top-left-align-text and run locally
- Copy this URL (https://graph.microsoft.com/v1.0/applications?$count=true) in the query textbox
- Run the query
- Click on toolkit component and observe fix
- Click on adaptive cards and observe fix

### CODE REVIEW

File: src/app/views/query-response/adaptive-cards/AdaptiveCard.tsx [hunk 1]
```diff
@@ -80,11 +84,10 @@ class AdaptiveCard extends Component<IAdaptiveCardProps> {
     if (body && !pending) {
       if (!data || (queryStatus && !queryStatus.ok)) {
         return (
-          <Label className={classes.emptyStateLabel}>
+          <Label className={classes.emptyStateLabel} styles={{root: this.textStyle}}>
```
Comment (ElinorW) [inline src/app/views/query-response/adaptive-cards/AdaptiveCard.tsx:87]: The className isn't needed here since the styling produces the desired effect. 
You can remove it

Comment (MaryannGitonga) [reply src/app/views/query-response/adaptive-cards/AdaptiveCard.tsx]: Done :)

**Review by ElinorW — APPROVED** [review]
