### PR TITLE
fix: add query input slice

### LINKED ISSUE #3203: Replace query-input actions, action creators and reducers with RTK slices

### LINKED ISSUE #3204: Replace query-status actions, action creators and reducers with RTK slices

### PR DESCRIPTION
**Pull request by musale**
### Description

Adds query input slice reducer (samples query)
Updated actions in various files

Closes #3203

### CODE REVIEW

File: src/app/services/reducers/index.ts [hunk 1]
```diff
@@ -12,7 +13,7 @@ import { graphExplorerMode } from './graph-explorer-mode-reducer';
 import { scopes } from './permissions-reducer';
 import { profile } from './profile-reducer';
 import { proxyUrl } from './proxy-url-reducer';
-import { sampleQuery } from './query-input-reducers';
+// import { sampleQuery } from './query-input-reducers';
```
Comment (thewahome) [inline src/app/services/reducers/index.ts:16]: We can delete this

Comment (thewahome) [reply src/app/services/reducers/index.ts:16]: The `query-input-reducers` and the associated test files can also be deleted since they are no longer in use
