### PR TITLE
fix: autocomplete-onfocusout

### LINKED ISSUE #721: Autocomplete doesn't collapse onFocusOut
**Describe the bug**
Autocomplete dropdown UI doesn't auto close when the address bar loses focus.

**To Reproduce**
1. Add a `/` in the URL bar
2. Click on any place else in the UI
3. See that the autocomplete UI doesn't close

The only way autocomplete closes is if I select an autocomplete option.

**Expected behavior**
When the URL bar loses focus, autocomplete dialog closes. 

**Screenshots**

image

**Desktop (please complete the following information):**
 - OS: Windows
 - Browsers: Edge and Chrome

 
[AB#7463](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7463)

### PR DESCRIPTION
**Pull request by thewahome**
## Overview
Autocomplete suggestions should collapse when the autocomplete component loses focus
Fixes #721 

### Demo

Optional. Screenshots, `curl` examples, etc.

### Notes

OnFocusOut is not supported in React hence the use of onBlur. 

## Testing Instructions

* Trigger an autocomplete call
* Once the options show up click outside the component
* Notice that the suggestions close

### CODE REVIEW

File: src/app/views/query-runner/query-input/auto-complete/AutoComplete.tsx [hunk 1]
```diff
@@ -402,6 +402,14 @@ class AutoComplete extends Component<IAutoCompleteProps, IAutoCompleteState> {
     return max;
   }
 
+  onFocusOut = (event: any) => {
```
Comment (jobala) [inline src/app/views/query-runner/query-input/auto-complete/AutoComplete.tsx:405]: What do you think of renaming this function to closeSuggestionDialog?

Comment (thewahome) [reply src/app/views/query-runner/query-input/auto-complete/AutoComplete.tsx:405]: Its purpose isn't to close the dialog. It's to monitor the focusOut event of the div and its children. closing the dialog could be the name of the function that closes the dialog and reused however since it's already a one-liner implementation that is explanatory, I do not exactly know the effect

Comment (jobala) [reply src/app/views/query-runner/query-input/auto-complete/AutoComplete.tsx:405]: From a user's perspective, what happens when the function is called?

Comment (thewahome) [reply src/app/views/query-runner/query-input/auto-complete/AutoComplete.tsx:405]: I see what you mean. What do you think of `handleClickOutside`? It encapsulates that we are handling a user's activity when they click outside. The reader may be misinformed by `closeSuggestionDialog` since they'd expect that this function is also called when someone selects a suggestion

**Comment by ElinorW** [comment]
There's an issue with regards to accessibility here, a user navigating the site using the Tab key won't be able to write a query or even edit one in the query input field.
It's inaccessible using the Tab key.

File: src/app/views/query-runner/query-input/auto-complete/AutoComplete.tsx (hunk 1 above)
Comment (jobala) [reply src/app/views/query-runner/query-input/auto-complete/AutoComplete.tsx:405]: @thewahome `handleClickOutside` does not communicate the intent because it doesn't clearly answer the question what does this function do? Can we rename the function that handles selecting a suggestion to `selectSuggestion` so as to avoid the ambiguity.

**Review by jobala — APPROVED** [review]

**Review by ElinorW — APPROVED** [review]
