### PR TITLE
Fix: Feedback rating

### LINKED ISSUE #1667: Fix the NPS scale to align with OCV scale
image

### PR DESCRIPTION
**Pull request by Onokaev**
## Overview
Fixes #1667 

### Demo
image

### Notes

Optional. Ancillary topics, caveats, alternative strategies that didn't work out, anything else.

## Testing Instructions

* How to test this PR
Check out this branch
Use the app for a minute
A feedback popup will appear with the new ratings

### CODE REVIEW

File: src/app/views/query-runner/request/feedback/uiStrings.ts [hunk 1]
```diff
@@ -6,7 +6,8 @@ export const uiStringMap: any = {
   Prompt_YesLabel: translateMessage('Sure'),
   Prompt_NoLabel: translateMessage('Sure'),
   Graph_Explorer_Rating_Question: translateMessage('Graph Rating Question'),
-  Rating_Values_1: `1 - ${translateMessage('Not at all likely')}`,
```
Comment (ElinorW) [inline src/app/views/query-runner/request/feedback/uiStrings.ts:9]: I know I had suggested removing the strings, this was because of the wrong interpretation on the OCV side. Now that everything is working as expected I think you can just return them
(i.e 0 - not at all likely and 10 - Extremely likely)

Comment (Onokaev) [reply src/app/views/query-runner/request/feedback/uiStrings.ts:9]: Awesome. Done
