### PR TITLE
Fix: sovereign clouds metadata

### LINKED ISSUE #670: $metadata query crashing Graph Explorer
Describe the bug
Quering $metadata for sovereign clouds crashes Graph Explorer in Chrome and returns error 401 in Microsoft Edge. But when you paste the query (https://microsoftgraph.chinacloudapi.cn/beta/$metadata)  directly on the browser, it runs correctly.
To Reproduce

Go to Graph Explorer
Paste this query to the address bar https://microsoftgraph.chinacloudapi.cn/beta/$metadata
Click run
See error

Expected behavior
When you paste the $metadata for a sovereign cloud, it should return results with no error.
Screenshots
Microsoft Edge

Chrome

Desktop (please complete the following information):

Smartphone (please complete the following information):

Additional context
[AB#5782](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/5782)

### PR DESCRIPTION
**Pull request by thewahome**
## Overview

Fixes #670 

### Demo

Anonymous
image

Logged in
image

### Notes

Optional. Ancillary topics, caveats, alternative strategies that didn't work out, anything else.

## Testing Instructions

* Run this query: https://microsoftgraph.chinacloudapi.cn/beta/$metadata
* Receive response

### CODE REVIEW

File: src/app/views/query-response/pivot-items/pivot-items.tsx [hunk 1]
```diff
@@ -105,13 +105,22 @@ function adaptiveCardPresentDot(sampleQuery: IQuery) {
...
   const language = 'json';
+  let contentType = null;
+
   if (headers) {
-    const contentType = headers['content-type'].split(';')[0];
+    const contentTypes = headers['content-type'];
+    if (contentTypes) {
+      const splitContentTypes = contentTypes.split(';');
+      if (splitContentTypes.length > 0) {
+        contentType = splitContentTypes[0];
```
Comment (ddyett) [inline src/app/views/query-response/pivot-items/pivot-items.tsx:117]: can you just add a comment about why the first is the one  to choose.
