### PR TITLE
Fix: Graph Explorer link colors

### LINKED ISSUE #707: Graph links do not meet the color-contrast ratio in dark theme
**Describe the bug**
The colour used on the links has a low colour contrast ratio, hence affecting visibility when in dark mode.

**To Reproduce**

**Expected behavior**
The Colour contrast ratio should be least 4.5:1 to ensure clear visibility

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge
 - Version: 87.0.637.0 (Official build) dev (64-bit)

**Smartphone (please complete the following information):**

**Additional context**
 
[AB#7462](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7462)

### PR DESCRIPTION
**Pull request by ElinorW**
## Overview

Fixes some link colours on GE to meet the colour-contrast ratio in dark mode.
Fixes #707 

### Demo

image

## Testing Instructions

* Open GE on your browser.
* Navigate to the 'More actions' icon and select 'Change theme'.
* Change theme to dark mode and close dialog box.
* Open dev tools and hold "Ctrl+Shift+C" to inspect elements.
* Hover above a link and observe contrast checkmark.

### CODE REVIEW

File: src/app/views/query-response/adaptive-cards/AdaptiveCard.tsx [hunk 1]
```diff
@@ -133,6 +133,7 @@ class AdaptiveCard extends Component<IAdaptiveCardProps> {
                 target='_blank'
                 rel='noopener noreferrer'
                 tabIndex={0}
+                style={queryResponseStyles(getTheme()).link}
```
Comment (thewahome) [inline src/app/views/query-response/adaptive-cards/AdaptiveCard.tsx:136]: We should use the classnames instead

**Review by thewahome — CHANGES_REQUESTED** [review]

**Comment by jobala** [comment]
@ElinorW does this solve color contrast issue when using the high contrast theme?

File: src/app/views/query-response/queryResponse.styles.ts [hunk 2]
```diff
@@ -18,7 +18,7 @@ export const queryResponseStyles = (theme: ITheme) => {
       alignItems: 'center',
     },
     link: {
-      color: theme.palette.blue,
+      color: theme.palette.themeDarkAlt,
```
Comment (thewahome) [inline src/app/views/query-response/queryResponse.styles.ts:21]: Noticed here that themeDarkAlt is applied, while the blueMid value was changed in the theme files. Does this still work?

**Comment by ElinorW** [comment]
> @ElinorW does this solve color contrast issue when using the high contrast theme?

@jobala Yeah it does for the links in the message bars.
I've had to change for those links present under the 'Toolkit Component' tab and 'Adaptive Cards' tab

File: src/app/views/query-response/queryResponse.styles.ts (hunk 2 above)
Comment (ElinorW) [reply src/app/views/query-response/queryResponse.styles.ts]: Wow, so I think I missed that I had changed the blueMid. Actually, I shall use the blueMid instead of the themeDarkAlt colour

File: src/types/adaptivecard.ts [hunk 3]
```diff
@@ -15,4 +15,5 @@ export interface IAdaptiveCardProps {
     getAdaptiveCard: Function;
   };
   queryStatus?: any;
+  styles?: object;
```
Comment (thewahome) [inline src/types/adaptivecard.ts:18]: This should not be necessary since messages/theme/style are passed down automatically

**Review by thewahome — APPROVED** [review]
