### PR TITLE
fix/Enable screen reader confirmation feedback

### LINKED ISSUE #796: Screen reader does not convey confirmation feedback after successfully adding 'Key' and 'Value' to the table present in the Request headers tab.
**Describe the bug**
If there is no notification of events relevant to user interactions, changes in the component’s state(s), value, name, description, or boundary it would be difficult for the platforms that provide Accessibility APIs, and would in turn affect the screen reader dependent users to determine the information of any new page , new dialog box etc. 

**To Reproduce**
1. Launch Narrator.
2. Open the URL in Anaheim edge dev browser.
3. Navigate to 'Request headers' tab present in the right side of the pane and activate it. 'Request headers' section will open.
4. Navigate and fill required details in the 'Key' and 'Value' edit box.
5. Navigate to the 'Add' button and activate it using enter key. Values of the 'Key' and 'Value' edit boxes gets successfully added in the table.
6. Observe the issue.

**Actual behaviour**
Screen reader does not convey confirmation feedback after successfully adding 'Key' and 'Value' values to the table present in the Request headers tab.

**Expected behaviour**
Screen reader should convey confirmation feedback after successfully adding 'Key' and 'Value' to the table present in the Request headers tab.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Win 10 Version 2004 (OS Build 20277.1)
- URL: https://developer.microsoft.com/en-us/graph/graph-explorer
- Browser:  Anaheim Edge Dev Version 89.0.731.0 (Official build) dev (64-bit)
- Screen Reader: Narrator

**Additional context**
1) Same issue is repro with NVDA.
2) Same issue is repro on activating Delete button present in this table under Request header tab. 
3) Same issue is repro on successfully activating 'Minimize Sidebar' button. 
4) This issue is repro for every actionable item that happened successfully present throughout the URL. 
[AB#7606](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7606)

### PR DESCRIPTION
**Pull request by ElinorW**
## Overview

Screen reader conveys confirmation feedback after successfully :
- adding 'Key' and 'Value' to the table present in the Request headers tab.
- deleting 'Key' and 'Value' on the table present in the Request headers tab.
- activating and deactivating 'Minimize sidebar button'
- activating the 'Expand' button in the Response area tab items.

fixes #796 

## Testing Instructions

1. Launch Narrator.
2. Open the URL in Anaheim edge dev browser.
3. Navigate to the 'Request headers' tab present in the right side of the pane and activate it. 'Request headers' section will open.
4. Navigate and fill the required details in the 'Key' and 'Value' edit box.
5. Navigate to the 'Add' button and activate it using enter key. Values of the 'Key' and 'Value' edit boxes gets successfully added in the table.
6. Observe the screen reader message.
7. Observe similar response upon deletion of the 'Key' and 'Value' Item.
8. Observe feedback on activating the 'Minimize sidebar button' and 'Expand' button

### CODE REVIEW

File: src/app/views/App.tsx [hunk 1]
```diff
@@ -66,6 +68,7 @@ interface IAppState {
   selectedVerb: string;
   mobileScreen: boolean;
   hideDialog: boolean;
+  onToggleSidebar: boolean;
```
Comment (thewahome) [inline src/app/views/App.tsx:71]: This variable is named like an event. Changing it to `isSidebarToggled` may help clarify it's purpose

Comment (ElinorW) [reply src/app/views/App.tsx:71]: Ah true, will do

File: src/app/views/App.tsx [hunk 2]
```diff
@@ -254,6 +258,9 @@ class App extends Component<IAppProps, IAppState> {
     const properties = { ...sidebarProperties };
     properties.showSidebar = !properties.showSidebar;
     this.props.actions!.toggleSidebar(properties);
+    this.setState(state => ({
+      onToggleSidebar: !this.state.onToggleSidebar
+    }));
```
Comment (thewahome) [inline src/app/views/App.tsx:263]: The global state has the state of the sidebar toggle. Creating a local state variable to capture this will be redundant and may have inconsistent results. The redux state is a better source of truth

**Review by thewahome — CHANGES_REQUESTED** [review]

File: src/app/views/query-runner/request/headers/RequestHeaders.tsx [hunk 3]
```diff
@@ -66,6 +69,7 @@ class RequestHeaders extends Component<IRequestHeadersProps, any> {
       this.setState({
         headerName: '',
         headerValue: '',
+        announcedMessage: translateMessage('Request Header added')
```
Comment (thewahome) [inline src/app/views/query-runner/request/headers/RequestHeaders.tsx:72]: Why does the announcedmessage need to go into the state?

Comment (ElinorW) [reply src/app/views/query-runner/request/headers/RequestHeaders.tsx:72]: I found it to be an easier way to change what's announced based on whether a user adds/deletes an item

**Review by thewahome — APPROVED** [review]

File: src/app/views/query-runner/request/headers/RequestHeaders.tsx [hunk 4]
```diff
@@ -1,57 +1,51 @@
...
+    setAnnouncedMessage(translateMessage('Request Header deleted'));
   };
 
-  private handleOnHeaderAdd = () => {
-    if (this.state.headerName !== '') {
-      const { headerName, headerValue } = this.state;
-      const { actions } = this.props;
-      let { sampleHeaders } = this.props.sampleQuery;
+  const handleOnHeaderAdd = () => {
+    if (headerName !== '') {
```
Comment (jobala) [inline src/app/views/query-runner/request/headers/RequestHeaders.tsx:47]: You can do `if (headerName) {}`

File: src/app/views/query-runner/request/headers/RequestHeaders.tsx [hunk 5]
```diff
@@ -63,76 +57,52 @@ class RequestHeaders extends Component<IRequestHeadersProps, any> {
...
-          </div>
-          <div className='col-sm-2 col-md-2'>
-            <PrimaryButton
-              style={{ width: '100%' }}
-              onClick={() => this.handleOnHeaderAdd()}>
-              <FormattedMessage id='Add' />
-            </PrimaryButton>
-          </div>
+  return (
+    <div style={container}>
```
Comment (jobala) [inline src/app/views/query-runner/request/headers/RequestHeaders.tsx:71]: Let's not pass inline styles because they become really hard to debug. Class names are easier to work with.

File: src/app/views/query-runner/request/headers/RequestHeaders.tsx [hunk 6]
```diff
@@ -63,76 +57,52 @@ class RequestHeaders extends Component<IRequestHeadersProps, any> {
...
+            className='header-input'
+            placeholder={messages.Value}
+            value={headerValue}
+            onChange={(event, value) => handleOnHeaderValueChange(value)}
+          />
+        </div>
+        <div className='col-sm-2 col-md-2'>
+          <PrimaryButton
+            style={{ width: '100%' }}
+            onClick={() => handleOnHeaderAdd()}>
```
Comment (jobala) [inline src/app/views/query-runner/request/headers/RequestHeaders.tsx:92]: Passing the function name will work as well `onClick={handleOnHeaderAdd}`

File: src/app/views/query-runner/request/headers/RequestHeaders.tsx [hunk 7]
```diff
@@ -63,76 +57,52 @@ class RequestHeaders extends Component<IRequestHeadersProps, any> {
...
-function mapStateToProps(state: any) {
-  return {
-    sampleQuery: state.sampleQuery,
-  };
-}
-
+      <hr />
+      <HeadersList
+        messages={messages}
+        handleOnHeaderDelete={(event: any, header: any) => handleOnHeaderDelete(header)}
```
Comment (jobala) [inline src/app/views/query-runner/request/headers/RequestHeaders.tsx:100]: Specifying types will help prevent type bugs.

**Review by jobala — CHANGES_REQUESTED** [review]

File: src/app/views/query-runner/request/headers/RequestHeaders.tsx (hunk 4 above)
Comment (ElinorW) [reply src/app/views/query-runner/request/headers/RequestHeaders.tsx:47]: sure thing

File: src/app/views/query-runner/request/headers/RequestHeaders.tsx (hunk 6 above)
Comment (ElinorW) [reply src/app/views/query-runner/request/headers/RequestHeaders.tsx:92]: sure

**Review by jobala — APPROVED** [review]
