### PR TITLE
Fixes preview collection button

### LINKED ISSUE #1326: [Resource Explorer] 'Preview collection' button not fitting properly in the layout
**Describe the bug**
When not selected, the preview collection button has the same background color as the layout where it sits but when selected, it is clear that it doesn't fit in size. 

**To Reproduce**
1. Go to Resource Explorer 
2. Add any resource to collection 
3. hover over preview collection button 

**Expected behavior**
Preview collection button should fit inside the layout 

**Screenshots**
preview collection

### PR DESCRIPTION
**Pull request by Onokaev**
## Overview
Fixes #1326 

### Demo
image
Light mode

image
Dark mode

image
High contrast mode

### Notes

Optional. Ancillary topics, caveats, alternative strategies that didn't work out, anything else.

## Testing Instructions

* How to test this PR
* Prefer bulleted description
* Start after checking out this branch
* Include any setup required, such as bundling scripts, restarting services, etc.
* Include test case, and expected output

### CODE REVIEW

File: src/app/views/sidebar/resource-explorer/CommandOptions.tsx [hunk 1]
```diff
@@ -26,13 +28,32 @@ const CommandOptions = (props: ICommandOptions) => {
     setIsOpen(open);
   }
 
+  const itemStyles: Partial<IContextualMenuItemStyles> = {
```
Comment (ElinorW) [inline src/app/views/sidebar/resource-explorer/CommandOptions.tsx:31]: Could we have the styles in their own file?

Comment (Onokaev) [reply src/app/views/sidebar/resource-explorer/CommandOptions.tsx:31]: Sure

**Review by ElinorW — APPROVED** [review]
