### PR TITLE
Fix: Canary urls crashing

### LINKED ISSUE #3063: Graph explorer crashing for canary endpoints
**Describe the bug**
We have been noticing from couple of days that when we use the canary endpoints to query in Graph explorer, the explorer crashes and session ends. 
This is what we see once the explorer has crashed.
image

### PR DESCRIPTION
**Pull request by ElinorW**
## Overview

Fixes #3063 

### Demo
https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/18407044/f92898d7-d367-4498-a9cf-961952248412

### Notes

Optional. Ancillary topics, caveats, alternative strategies that didn't work out, anything else.

## Testing Instructions

* Check out PR
* Load GE
* Paste test link  `https://canary.graph.microsoft.com/testprodbetatamy-pps-offboarding/me/insights/trending`
* Click anywhere on the page and observe the page doesn't crash

### CODE REVIEW

**Review by thewahome — APPROVED** [review]

File: src/app/utils/query-url-sanitization.ts [hunk 1]
```diff
@@ -102,7 +102,7 @@ function sanitizedQueryUrl(url: string): string {
  * @param segment
  */
 function sanitizePathSegment(previousSegment: string, segment: string): string {
-  const segmentsToIgnore = ['$value', '$count', '$ref', '$batch'];
+  const segmentsToIgnore = ['$value', '$count', '$ref', '$batch', '$metadata'];
```
Comment (thewahome) [inline src/app/utils/query-url-sanitization.ts:105]: Would a check for whether the segment starts with a dollar sign help prevent growing this list?

Comment (ElinorW) [reply src/app/utils/query-url-sanitization.ts:105]: Yeah that's a great suggestion

**Review by thewahome — APPROVED** [review]
