### PR TITLE
Fix: Accessibility bugs (Jul-Sep)

### LINKED ISSUE #1005: Accessibility Issues
**Describe the bug**
Various accessibility issues raised by the Unified Dev Portal & Infrastructure team.

**Additional context**
[List of Accessibility issues](https://office.visualstudio.com/OC/_workitems/assignedtome/)
 
[AB#10072](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10072)

### PR DESCRIPTION
**Pull request by ElinorW**
## Overview
Fixes #1005 
This PR fixes a number of existing accessibility issues:

#### 1) History tab
- Corrected the keyboard focus order, when navigating to the **Delete** and **Export** buttons
- Updated the aria labels for the **Delete** and **Export** buttons
- Addition of tooltips on the icons used

#### 2) Authentication area
- Changed the **sign-in message** to a warning message, to enable better screen reader use and for easy visibility.

#### 3) Adaptive card tab
- Added an aria-label for the **copy** button

#### 4) Request Headers tab
- Added aria-labels to the columns
- Added a column name for the last unnamed column 

#### 5) Sample Queries tab
- Added the **navigation** role
- Add aria-label for the group names for screen readers to narrate both the **group title** and the **group count**

#### 6) Graph Toolkit
- Added the title property for the **iframe** used

#### 7) Share Query tab
- Added an aria-label for the **textarea** for screen reader user

### Demo
_Sign-in warning message_
image

### CODE REVIEW

File: src/app/views/query-runner/request/headers/HeadersList.tsx [hunk 1]
```diff
@@ -42,23 +42,23 @@ const HeadersList = ({
   };
 
   const columns = [
-    { key: 'key', name: messages.Key, fieldName: 'name', minWidth: 300, maxWidth: 400 },
-    { key: 'value', name: messages.Value, fieldName: 'value', minWidth: 300, maxWidth: 400 },
-    { key: 'button', name: '', fieldName: 'button', minWidth: 200, maxWidth: 300 }
+    { key: 'key', name: translateMessage('Key'), fieldName: 'name', minWidth: 300, maxWidth: 400, ariaLabel: translateMessage('Key') },
+    { key: 'value', name: translateMessage('Value'), fieldName: 'value', minWidth: 300, maxWidth: 400, ariaLabel: translateMessage('Value') },
+    { key: 'button', name: translateMessage('actions'), fieldName: 'button', minWidth: 200, maxWidth: 300, ariaLabel: translateMessage('actions') }
```
Comment (thewahome) [inline src/app/views/query-runner/request/headers/HeadersList.tsx:47]: The `actions` key should be added to `GE.json`

Comment (ElinorW) [reply src/app/views/query-runner/request/headers/HeadersList.tsx:47]: Yeah, it was already added actually

**Review by thewahome — APPROVED** [review]

**Comment by ElinorW** [comment]
> @ElinorW Did we decide against changing the authentication text to `You are currently using a sample account. Sign in to access your own data.`?

No, we didn't. Let me update that
